// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    _LNaviAnchor: typeof import('./src/components/LNaviAnchor/_LNaviAnchor.vue')['default']
    ElSvgIcon: typeof import('./src/components/ElSvgIcon.vue')['default']
    LForm: typeof import('./src/components/LForm/LForm.vue')['default']
    LNaviAnchor: typeof import('./src/components/LNaviAnchor/LNaviAnchor.vue')['default']
    'LNaviAnchor copy': typeof import('./src/components/LNaviAnchor/LNaviAnchor copy.vue')['default']
    LSearch: typeof import('./src/components/LSearch/LSearch.vue')['default']
    'LSearch copy': typeof import('./src/components/LSearch/LSearch copy.vue')['default']
    LSearchItem: typeof import('./src/components/LSearch/LSearchItem.vue')['default']
    LSearchLayout: typeof import('./src/components/LSearchLayout/LSearchLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
